services:
  app:
    container_name: sprentor
    build: .
    env_file:
      - .env.docker
    volumes:
      - db_data:/app/prisma
      - downloads:/app/downloads
    networks:
      - shared
    restart: unless-stopped

volumes:
  db_data:
  downloads:

networks:
  shared:
    name: home-server-setup_default
    external: true