services:
  app:
    container_name: sprentor
    build: .
    env_file:
      - .env.docker
    volumes:
      - ${DB_PATH}:/app/prisma/data
      - ${DOWNLOADS_PATH}:/app/downloads
      - ${DATA_PATH}:/app/data
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    name: home-server-net
    external: true